name: eazy_state
description: A lightweight and straightforward state management solution for Flutter applications.
repository: https://github.com/EasyFlutterApps/eazy_state
version: 0.1.1

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
